### ISSUE TITLE
Difficulty with Installation when Using Zen AppImage

### ISSUE THREAD

**Issue by YouCanTouCan** [wysh3/zen-premium#3]
I know I'm likely doing something very stupid, but I'm having trouble installing this. I have the Zen Browser AppImage, version b-5, installed on my Fedora 41 KDE Spin computer. I have done the following steps:

1. Downloaded the contents of the program folder from fx-autoconfig and placed them in Home/.zen
2. Downloaded the contents of the profile folder from fx-autoconfig and placed them in my profile's chrome folder (merging the userchrome.css with the one I already had)
3. Downloaded all the files from this repository and placed them in my profile's chrome/JS
4. Downloaded ollama per the website and pulled the specified model, using the command line
5. Cleared the startup cache from about:support
6. Restarted zen browser

But unfortunately, seemingly nothing has happened. My main suspicion is that I put the program folder files in the wrong location, but with Zen installed as an AppImage I'm unsure where exactly they should go. Any ideas what I could be doing wrong or suggestions for how to get it working?

**Comment by wysh3** [comment]
> Downloaded the contents of the program folder from fx-autoconfig and placed them in Home/.zen

you can't do this if you're using app image
prolly try the below steps and you might need to repeat the same with every update (better just use tarball)

1. Extract the AppImage:

    ``"$HOME/.local/share/AppImage/ZenBrowser.AppImage" --appimage-extract``

2 .Copy the contents of the program folder (such as config.js and defaults/) into the extracted 
     
   ```squashfs-root/```

3. Repackage the AppImage using appimagetool:
 
   ``appimagetool "$HOME/squashfs-root"``

4. Rename the new AppImage and overwrite the old one:

   ``mv "$HOME/Zen_Browser-x86_64.AppImage" "$HOME/.local/share/AppImage/ZenBrowser.AppImage"``

**Comment by YouCanTouCan** [comment]
> (better just use tarball)

I definitely agree with this sentiment - I opted for AppImage since I find it easier than tarballs generally, but these steps make it hard enough where I found swapping to the tarball version much simpler. Having done so, I can happily say that I got it working perfectly. Thank you!
